// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/space/dao/internal"
)

// internalAddonsSpaceTypeDao is internal type for wrapping internal DAO implements.
type internalAddonsSpaceTypeDao = *internal.AddonsSpaceTypeDao

// addonsSpaceTypeDao is the data access object for table addons_space_type.
// You can define custom methods on it to extend its functionality as you wish.
type addonsSpaceTypeDao struct {
	internalAddonsSpaceTypeDao
}

var (
	// AddonsSpaceType is globally public accessible object for table addons_space_type operations.
	AddonsSpaceType = addonsSpaceTypeDao{
		internal.NewAddonsSpaceTypeDao(),
	}
)

// Fill with you ideas below.
