// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/space/dao/internal"
)

// internalAddonsSpaceInfoDao is internal type for wrapping internal DAO implements.
type internalAddonsSpaceInfoDao = *internal.AddonsSpaceInfoDao

// addonsSpaceInfoDao is the data access object for table addons_space_info.
// You can define custom methods on it to extend its functionality as you wish.
type addonsSpaceInfoDao struct {
	internalAddonsSpaceInfoDao
}

var (
	// AddonsSpaceInfo is globally public accessible object for table addons_space_info operations.
	AddonsSpaceInfo = addonsSpaceInfoDao{
		internal.NewAddonsSpaceInfoDao(),
	}
)

// Fill with you ideas below.
