// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/dict/dao/internal"
)

// internalAddonsDictInfoDao is internal type for wrapping internal DAO implements.
type internalAddonsDictInfoDao = *internal.AddonsDictInfoDao

// addonsDictInfoDao is the data access object for table addons_dict_info.
// You can define custom methods on it to extend its functionality as you wish.
type addonsDictInfoDao struct {
	internalAddonsDictInfoDao
}

var (
	// AddonsDictInfo is globally public accessible object for table addons_dict_info operations.
	AddonsDictInfo = addonsDictInfoDao{
		internal.NewAddonsDictInfoDao(),
	}
)

// Fill with you ideas below.
