// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/dict/dao/internal"
)

// internalAddonsDictTypeDao is internal type for wrapping internal DAO implements.
type internalAddonsDictTypeDao = *internal.AddonsDictTypeDao

// addonsDictTypeDao is the data access object for table addons_dict_type.
// You can define custom methods on it to extend its functionality as you wish.
type addonsDictTypeDao struct {
	internalAddonsDictTypeDao
}

var (
	// AddonsDictType is globally public accessible object for table addons_dict_type operations.
	AddonsDictType = addonsDictTypeDao{
		internal.NewAddonsDictTypeDao(),
	}
)

// Fill with you ideas below.
