// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysMemberDao is internal type for wrapping internal DAO implements.
type internalBaseSysMemberDao = *internal.BaseSysMemberDao

// baseSysMemberDao is the data access object for table base_sys_member.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysMemberDao struct {
	internalBaseSysMemberDao
}

var (
	// BaseSysMember is globally public accessible object for table base_sys_member operations.
	BaseSysMember = baseSysMemberDao{
		internal.NewBaseSysMemberDao(),
	}
)

// Fill with you ideas below.
