// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysMemberAttrDao is internal type for wrapping internal DAO implements.
type internalBaseSysMemberAttrDao = *internal.BaseSysMemberAttrDao

// baseSysMemberAttrDao is the data access object for table base_sys_member_attr.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysMemberAttrDao struct {
	internalBaseSysMemberAttrDao
}

var (
	// BaseSysMemberAttr is globally public accessible object for table base_sys_member_attr operations.
	BaseSysMemberAttr = baseSysMemberAttrDao{
		internal.NewBaseSysMemberAttrDao(),
	}
)

// Fill with you ideas below.
