// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysUserDao is internal type for wrapping internal DAO implements.
type internalBaseSysUserDao = *internal.BaseSysUserDao

// baseSysUserDao is the data access object for table base_sys_user.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysUserDao struct {
	internalBaseSysUserDao
}

var (
	// BaseSysUser is globally public accessible object for table base_sys_user operations.
	BaseSysUser = baseSysUserDao{
		internal.NewBaseSysUserDao(),
	}
)

// Fill with you ideas below.
