// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysAddonsDao is internal type for wrapping internal DAO implements.
type internalBaseSysAddonsDao = *internal.BaseSysAddonsDao

// baseSysAddonsDao is the data access object for table base_sys_addons.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysAddonsDao struct {
	internalBaseSysAddonsDao
}

var (
	// BaseSysAddons is globally public accessible object for table base_sys_addons operations.
	BaseSysAddons = baseSysAddonsDao{
		internal.NewBaseSysAddonsDao(),
	}
)

// Fill with you ideas below.
