// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysInitDao is internal type for wrapping internal DAO implements.
type internalBaseSysInitDao = *internal.BaseSysInitDao

// baseSysInitDao is the data access object for table base_sys_init.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysInitDao struct {
	internalBaseSysInitDao
}

var (
	// BaseSysInit is globally public accessible object for table base_sys_init operations.
	BaseSysInit = baseSysInitDao{
		internal.NewBaseSysInitDao(),
	}
)

// Fill with you ideas below.
