// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysUserRoleDao is internal type for wrapping internal DAO implements.
type internalBaseSysUserRoleDao = *internal.BaseSysUserRoleDao

// baseSysUserRoleDao is the data access object for table base_sys_user_role.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysUserRoleDao struct {
	internalBaseSysUserRoleDao
}

var (
	// BaseSysUserRole is globally public accessible object for table base_sys_user_role operations.
	BaseSysUserRole = baseSysUserRoleDao{
		internal.NewBaseSysUserRoleDao(),
	}
)

// Fill with you ideas below.
