// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseEpsAdminDao is internal type for wrapping internal DAO implements.
type internalBaseEpsAdminDao = *internal.BaseEpsAdminDao

// baseEpsAdminDao is the data access object for table base_eps_admin.
// You can define custom methods on it to extend its functionality as you wish.
type baseEpsAdminDao struct {
	internalBaseEpsAdminDao
}

var (
	// BaseEpsAdmin is globally public accessible object for table base_eps_admin operations.
	BaseEpsAdmin = baseEpsAdminDao{
		internal.NewBaseEpsAdminDao(),
	}
)

// Fill with you ideas below.
