// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysLogDao is internal type for wrapping internal DAO implements.
type internalBaseSysLogDao = *internal.BaseSysLogDao

// baseSysLogDao is the data access object for table base_sys_log.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysLogDao struct {
	internalBaseSysLogDao
}

var (
	// BaseSysLog is globally public accessible object for table base_sys_log operations.
	BaseSysLog = baseSysLogDao{
		internal.NewBaseSysLogDao(),
	}
)

// Fill with you ideas below.
