// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysAddonsTypeDao is internal type for wrapping internal DAO implements.
type internalBaseSysAddonsTypeDao = *internal.BaseSysAddonsTypeDao

// baseSysAddonsTypeDao is the data access object for table base_sys_addonsType.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysAddonsTypeDao struct {
	internalBaseSysAddonsTypeDao
}

var (
	// BaseSysAddonsType is globally public accessible object for table base_sys_addonsType operations.
	BaseSysAddonsType = baseSysAddonsTypeDao{
		internal.NewBaseSysAddonsTypeDao(),
	}
)

// Fill with you ideas below.
