// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// internalBaseSysRoleDao is internal type for wrapping internal DAO implements.
type internalBaseSysRoleDao = *internal.BaseSysRoleDao

// baseSysRoleDao is the data access object for table base_sys_role.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysRoleDao struct {
	internalBaseSysRoleDao
}

var (
	// BaseSysRole is globally public accessible object for table base_sys_role operations.
	BaseSysRole = baseSysRoleDao{
		internal.NewBaseSysRoleDao(),
	}
)

// Fill with you ideas below.
