// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/task/dao/internal"
)

// internalAddonsTaskLogDao is internal type for wrapping internal DAO implements.
type internalAddonsTaskLogDao = *internal.AddonsTaskLogDao

// addonsTaskLogDao is the data access object for table addons_task_log.
// You can define custom methods on it to extend its functionality as you wish.
type addonsTaskLogDao struct {
	internalAddonsTaskLogDao
}

var (
	// AddonsTaskLog is globally public accessible object for table addons_task_log operations.
	AddonsTaskLog = addonsTaskLogDao{
		internal.NewAddonsTaskLogDao(),
	}
)

// Fill with you ideas below.
